# Arreglos en Numpy

In [2]:
import numpy as np

#Generando un array random
data = np.random.randn(2,3)
print(data)

[[ 1.16796124 -0.20345033  0.02887012]
 [ 1.58728571 -0.15896111 -0.3799295 ]]


In [3]:
# Operaciones sobre arreglos
# Multiplica cada elemento por 10, y suma cada elemento consigo mismo
data *  10, data + data

(array([[11.67961239, -2.03450327,  0.28870116],
        [15.8728571 , -1.5896111 , -3.799295  ]]),
 array([[ 2.33592248, -0.40690065,  0.05774023],
        [ 3.17457142, -0.31792222, -0.759859  ]]))

In [6]:
# Crea un array de Numpy a partir de un array de Python
data = [[1,2,3], [4,5,6]]
arr = np.array(data)

print(data)
print(arr)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [10]:
# Shape da las distintas dimensiones de los arreglos (en este caso dos arreglos de tres elementos cada uno)
# ndim da el largo total de la colección
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [13]:
# Arreglos de ceros
np.zeros((2,3))

# Crea un arreglo entre 0 y 9
np.arange(10)

# Crea un arreglo de valores espaciados de igual manera entre sí
# Este ejemplo creará un array de 6 elementos entre 1 y 4
np.linspace (1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

# Slicing de una dimensión

In [21]:
arr = np.arange(8)
arr[5]
arr[2:5] # Muestra las posiciones 2 a 5
arr[2:5] = 58 # Asigna a las posiciones 2 a 5 el número 58
# arr[:] = 58 # Asigna a todas las posiciones el número 58
arr

array([ 0,  1, 58, 58, 58,  5,  6,  7])

# Slicing con dos dimensiones

In [41]:
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

arr2d

print(arr2d[:2])

print(arr2d[:2, 1:])
arr2d[1, :2]

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


array([4, 5])

In [47]:
# start:stop:step
# las posiciones entre 1 y 7 saltando de 2 en 2
arr[1:7:2]
# Vuelve hacia atrás en la colección
arr[-3:7]

array([5, 6])

In [49]:
# Filtros booleanos
arr2d < 2 # compara cada elemento con la condición

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [52]:
soyarr = np.arange(10)
soyarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# Funciones universales

np.sqrt(soyarr)
np.abs(soyarr)
np.square(soyarr)
np.add(soyarr, soyarr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [60]:
# Funciones de agregación
newarr = np.random.randn(5,4)
newarr

array([[-1.71395734, -0.533106  ,  1.70106651,  1.198981  ],
       [ 0.66507382, -0.17366564,  0.84017003, -0.84217379],
       [-1.05721197,  0.25163118, -0.25897786,  0.77955377],
       [ 2.33339694,  0.57438073,  0.35816131,  2.26701206],
       [-0.67223997,  0.02395942,  0.52420367, -0.49426987]])

In [63]:
newarr.mean() #promedio de todos los valores
newarr.sum() #suma d etodos los elementos
newarr.prod() #producto de todos los elementos


3.714675857761714e-05